clc; clear; close all;

%% Make DFF Videos
make_video('../../../data/cityscapes-preprocess/data_proc/leftImg8bit/demoVideo/stuttgart_00',...
    '../../../exps/cityscapes/result/test/demoVideo_stuttgart_00/dff/pred_color',...
    '../../../exps/cityscapes/result/video', 'demoVideo_stuttgart_00_dff', 17, 100);
make_video('../../../data/cityscapes-preprocess/data_proc/leftImg8bit/demoVideo/stuttgart_01',...
    '../../../exps/cityscapes/result/test/demoVideo_stuttgart_01/dff/pred_color',...
    '../../../exps/cityscapes/result/video', 'demoVideo_stuttgart_01_dff', 17, 100);
make_video('../../../data/cityscapes-preprocess/data_proc/leftImg8bit/demoVideo/stuttgart_02',...
    '../../../exps/cityscapes/result/test/demoVideo_stuttgart_02/dff/pred_color',...
    '../../../exps/cityscapes/result/video', 'demoVideo_stuttgart_02_dff', 17, 100);

%% Make DFF Class-Wise Videos
make_clswise('../../../data/cityscapes-preprocess/data_proc/leftImg8bit/demoVideo/stuttgart_00',...
    '../../../exps/cityscapes/result/test/demoVideo_stuttgart_00/dff',...
    '../../../exps/cityscapes/result/video', 'demoVideo_stuttgart_00_dff_clswise', 17, 100);
make_clswise('../../../data/cityscapes-preprocess/data_proc/leftImg8bit/demoVideo/stuttgart_01',...
    '../../../exps/cityscapes/result/test/demoVideo_stuttgart_01/dff',...
    '../../../exps/cityscapes/result/video', 'demoVideo_stuttgart_01_dff_clswise', 17, 100);
make_clswise('../../../data/cityscapes-preprocess/data_proc/leftImg8bit/demoVideo/stuttgart_02',...
    '../../../exps/cityscapes/result/test/demoVideo_stuttgart_02/dff',...
    '../../../exps/cityscapes/result/video', 'demoVideo_stuttgart_02_dff_clswise', 17, 100);

%% Make DFF-CASENet Comparison Videos
make_compare('../../../data/cityscapes-preprocess/data_proc/leftImg8bit/demoVideo/stuttgart_00',...
    '../../../exps/cityscapes/result/test/demoVideo_stuttgart_00/dff/pred_color',...
    '../../../exps/cityscapes/result/test/demoVideo_stuttgart_00/casenet/pred_color',...
    '../../../exps/cityscapes/result/video', 'demoVideo_stuttgart_00_compare', 17, 100);

make_compare('../../../data/cityscapes-preprocess/data_proc/leftImg8bit/demoVideo/stuttgart_01',...
    '../../../exps/cityscapes/result/test/demoVideo_stuttgart_01/dff/pred_color',...
    '../../../exps/cityscapes/result/test/demoVideo_stuttgart_01/casenet/pred_color',...
    '../../../exps/cityscapes/result/video', 'demoVideo_stuttgart_01_compare', 17, 100);

make_compare('../../../data/cityscapes-preprocess/data_proc/leftImg8bit/demoVideo/stuttgart_02',...
    '../../../exps/cityscapes/result/test/demoVideo_stuttgart_02/dff/pred_color',...
    '../../../exps/cityscapes/result/test/demoVideo_stuttgart_02/casenet/pred_color',...
    '../../../exps/cityscapes/result/video', 'demoVideo_stuttgart_02_compare', 17, 100);

%% Make Test Result Video
make_test('../../../data/cityscapes-preprocess/data_proc',...
    '../../../data/cityscapes-preprocess/data_proc/val.mat',...
    '../../../exps/cityscapes/result/visualize/val',...
    '../../../exps/cityscapes/result/test/val/dff/pred_color',...
    '../../../exps/cityscapes/result/test/val/casenet/pred_color',...
    '../../../exps/cityscapes/result/video', 'val', 0.5, 100);